#!/usr/bin/env bash
#
# Render and install `~/.pyronaut/settings.toml` from the action's inputs.
#
# Pyronaut reads its Maven repositories and native-launcher source from this
# file and folds both into the identity of its setup manifest, so the file has
# to be in place before `pyronaut setup` runs and its contents belong in the SDK
# cache key.
#
# That splits the work in two, because the file lives inside the directory the
# SDK cache covers:
#
#   render  compute the contents and their hash, before the cache key is built
#   apply   copy the rendered file into ~/.pyronaut, after the cache is restored
#
# Applying after the restore is what stops a cache entry matched through a
# restore-key prefix from reinstating a settings.toml this run did not ask for.
set -euo pipefail
# shellcheck source=scripts/common.sh
. "$(dirname "$0")/common.sh"

mode="${1:-render}"
rendered_file="${RUNNER_TEMP:-/tmp}/setup-pyronaut/settings.toml"
settings_file="$PYRONAUT_HOME/settings.toml"

toml_string() {
  # TOML basic strings escape backslashes and double quotes.
  printf '"%s"' "$(printf '%s' "$1" | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g')"
}

render() {
  local sections="" entries="" native_images="" repositories repository

  repositories="$(meaningful_lines "${INPUT_MAVEN_REPOSITORIES:-}")"
  if [ -n "$repositories" ]; then
    while IFS= read -r repository; do
      [ -n "$repository" ] || continue
      entries="$entries  $(toml_string "$repository"),
"
    done <<EOF
$repositories
EOF
    sections="${sections}[maven]
repositories = [
$entries]

"
  fi

  if [ -n "${INPUT_NATIVE_IMAGES_BASE_URL:-}" ]; then
    native_images="${native_images}base-url = $(toml_string "$INPUT_NATIVE_IMAGES_BASE_URL")
"
  fi
  if [ -n "${INPUT_NATIVE_IMAGES_VERSION:-}" ]; then
    native_images="${native_images}version = $(toml_string "$INPUT_NATIVE_IMAGES_VERSION")
"
  fi
  if [ -n "${INPUT_NATIVE_IMAGES_RELEASE_TAG:-}" ]; then
    native_images="${native_images}release-tag = $(toml_string "$INPUT_NATIVE_IMAGES_RELEASE_TAG")
"
  fi
  if [ -n "$native_images" ]; then
    sections="${sections}[native-images]
$native_images
"
  fi

  [ -z "$sections" ] && return 1

  mkdir -p "$(dirname "$rendered_file")"
  {
    printf '# Generated by micronaut-projects/setup-pyronaut. Do not edit.\n'
    printf '%s' "$sections"
  } >"$rendered_file"
  return 0
}

case "$mode" in
  render)
    if render; then
      group "Rendered Pyronaut settings"
      cat "$rendered_file"
      endgroup
      set_output "rendered" "$rendered_file"
      set_output "settings-hash" "$(short_hash <"$rendered_file")"
    elif [ -f "$settings_file" ]; then
      # A settings.toml the workflow wrote itself is the configuration for this
      # run: adopt it, so that it survives the cache restore and takes part in
      # the cache key just like a rendered one would.
      mkdir -p "$(dirname "$rendered_file")"
      cp "$settings_file" "$rendered_file"
      printf 'No settings inputs given; keeping the existing %s\n' "$settings_file"
      set_output "rendered" "$rendered_file"
      set_output "settings-hash" "existing-$(short_hash <"$rendered_file")"
    else
      rm -f "$rendered_file"
      printf 'No settings inputs given; using Pyronaut defaults.\n'
      set_output "rendered" ""
      set_output "settings-hash" "none"
    fi
    ;;
  apply)
    if [ -f "$rendered_file" ]; then
      mkdir -p "$PYRONAUT_HOME"
      cp "$rendered_file" "$settings_file"
      printf 'Installed %s\n' "$settings_file"
    elif [ -f "$settings_file" ]; then
      # This run wants Pyronaut's defaults, but a cache entry matched through a
      # restore-key prefix brought an older settings.toml back. Drop it, or
      # setup would resolve against configuration nothing asked for.
      rm -f "$settings_file"
      printf 'Removed a stale %s restored from the cache.\n' "$settings_file"
    fi
    ;;
  *)
    fail "Unknown mode: $mode (expected 'render' or 'apply')"
    ;;
esac
